---
name: Bug Report
about: Create a report to help us improve
title: '[BUG] '
labels: ['bug']
assignees: ''
---

## 🐛 Bug Description
A clear and concise description of what the bug is.

## 🔄 To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## ✅ Expected Behavior
A clear and concise description of what you expected to happen.

## 📸 Screenshots
If applicable, add screenshots to help explain your problem.

## 🖥️ Environment
- **OS**: [e.g. macOS 13.0, Windows 11, Ubuntu 22.04]
- **Python Version**: [e.g. 3.9.0]
- **Framework Version**: [e.g. 2.0.0]
- **Installation Method**: [e.g. pip, git clone]

## 📋 Additional Context
Add any other context about the problem here.

## 🔍 Error Logs
```
Paste any relevant error messages or logs here
```

## ✅ Checklist
- [ ] I have searched existing issues
- [ ] I have provided all required information
- [ ] I can reproduce this issue consistently
